// src/mindsight/components/core/MindsightRoot.tsx
import type { Component } from "solid-js"
import { Mindsight, MindsightContext } from "../../Mindsight"
import { getFakeServerClient } from "../../serverClient/FakeServerClient"
import { Sandbox } from "../canvas/Sandbox.solid"
import "solid-devtools"
import { attachDevtoolsOverlay } from "@solid-devtools/overlay"

attachDevtoolsOverlay()

export const MindsightRoot: Component<{
  instanceId: string
}> = props => {
  const app = new Mindsight(props.instanceId, getFakeServerClient())

  return (
    <MindsightContext.Provider value={{ ...app }}>
      <Sandbox />
    </MindsightContext.Provider>
  )
}

// src/mindsight/components/core/MindsightRoot.svelte
<script lang="ts">
  import { setContext } from "svelte"
  import { Mindsight } from "../../Mindsight"
  import { getFakeServerClient } from "../../serverClient/FakeServerClient"
  import { pick } from "lodash"
  import Sandbox from "../canvas/Sandbox.svelte"

  export let instanceId: string

  const app = new Mindsight(instanceId, getFakeServerClient())

  setContext(
    "mindsight",
    pick(app, ["db", "canvas", "instanceId", "server", "information"]),
  )
</script>

<Sandbox />
