// src/mindsight/components/canvas/CanvasObject.solid.tsx
import { Switch, type Component, Match, createEffect, Show, onCleanup } from "solid-js"
import { useMindsight } from "../../Mindsight"
import { createDexieSignalQuery } from "solid-dexie"
import { Card } from "./Card.solid"
import { memo } from "../../utils"
import { CanvasObjectProvider } from "./contexts/useCanvasObject"

export const CanvasObject: Component<{
  id: string
  onDragStart: (e: { x: number; y: number }) => void
  onDrag: (e: { x: number; y: number }) => void
  onDragEnd: (e: { x: number; y: number }) => void
}> = props => {
  const app = useMindsight()

  const object = createDexieSignalQuery(() => app.canvas.getCanvasObject(props.id))

  const informationId = memo(() => object()?.informationId)

  const handleDragStart = (e: DragEvent) => {
    e.dataTransfer?.setData("text/plain", object()?.id || "")
    e.dataTransfer?.setDragImage(document.createElement("span"), 0, 0)
    e.dataTransfer!.effectAllowed = "move"

    props.onDragStart({ x: e.clientX, y: e.clientY })
  }

  const handleDrag = (e: DragEvent) => {
    props.onDrag({ x: e.clientX, y: e.clientY })
  }

  const handleDragEnd = (e: DragEvent) => {
    props.onDragEnd({ x: e.clientX, y: e.clientY })
  }

  const handleSelect = async (e: MouseEvent) => {
    e.stopPropagation()
    if (e.shiftKey) {
      if (object()?.isSelected) {
        await app.canvas.deselectCanvasObject(object()?.id ?? "")
        return
      }
      await app.canvas.selectCanvasObject(object()?.id ?? "")
      return
    }
    if (object()?.isSelected) return
    await app.canvas.deselectAllCanvasObjects()
    await app.canvas.selectCanvasObject(object()?.id ?? "")
  }

  return (
    <CanvasObjectProvider
      registerDragger={(el, v) => {
        el.draggable = Boolean(object()?.isDraggable && object()?.isSelected)

        function handleOnMouseEnter(e: MouseEvent) {
          e.target.style.cursor = "grab"
          e.target.draggable = object?.()?.isDraggable && object?.()?.isSelected
        }

        function handleOnMouseLeave(e: MouseEvent) {
          e.target.style.cursor = "auto"
          e.target.draggable = false
        }

        el.addEventListener("mouseenter", handleOnMouseEnter)
        el.addEventListener("mouseleave", handleOnMouseLeave)

        onCleanup(() => {
          el.removeEventListener("mouseenter", handleOnMouseEnter)
          el.removeEventListener("mouseleave", handleOnMouseLeave)
        })
      }}
      canvasObject={object}
    >
      <Show when={object() !== undefined}>
        <div
          id={`canvas-object:${object()?.id}`}
          class="absolute top-0 left-0"
          style={{
            transform: `translate(${object()?.x}px, ${object()?.y}px)`,
          }}
          onDragStart={handleDragStart}
          onDrag={handleDrag}
          onDragEnd={handleDragEnd}
          onClick={handleSelect}
        >
          <Switch fallback={<></>}>
            <Match when={object()?.type === "card"}>
              <Card id={props.id} informationId={informationId.$} />
            </Match>
          </Switch>
        </div>
      </Show>
    </CanvasObjectProvider>
  )
}

// src/mindsight/components/canvas/CanvasObject.svelte
<script lang="ts" context="module">
  export function registerDragger(element: HTMLElement, canvasObject: ICanvasObject) {
    const handleMouseDown = (e: MouseEvent) => {
      if (!canvasObject.isSelected) {
        return
      }
      e.target.setAttribute("draggable", "true")
    }
    const handleDragEnd = (e: DragEvent) => {
      if (!canvasObject.isDragging) {
        return
      }
      e.target.setAttribute("draggable", "false")
    }

    element.addEventListener("mousedown", handleMouseDown)
    element.addEventListener("dragend", handleDragEnd)

    return {
      destroy() {
        element.removeEventListener("mousedown", handleMouseDown)
        element.removeEventListener("dragend", handleDragEnd)
      },
    }
  }
</script>

<script lang="ts">
  import { createEventDispatcher, getContext, onMount, setContext } from "svelte"
  import Card from "./Card.svelte"
  import type { ICanvasObject } from "../../interfaces/ICanvasObject"
  import type { IMindsightContext } from "../../Mindsight"
  import { liveQuery } from "dexie"

  const app = getContext<IMindsightContext>("mindsight")

  export let canvasObject: ICanvasObject
  const dispatch = createEventDispatcher<{
    dragstart: { id: string; x: number; y: number }
    drag: { id: string; x: number; y: number }
    dragend: { id: string; x: number; y: number }
  }>()

  $: information = liveQuery(() =>
    app.information.getInformation(canvasObject.informationId!),
  )

  const handleDragEvent = async (e: DragEvent) => {
    if (e.type === "dragstart") {
      e.dataTransfer!.setData("text/plain", canvasObject.id)
      e.dataTransfer?.setDragImage(document.createElement("span"), 0, 0)
      e.dataTransfer!.effectAllowed = "copyMove"
    }

    dispatch(e.type, { id: canvasObject.id, x: e.clientX, y: e.clientY })
  }

  const handleSelect = async (e: MouseEvent) => {
    e.stopPropagation()
    if (e.shiftKey) {
      if (canvasObject.isSelected) {
        await app.canvas.deselectCanvasObject(canvasObject.id)
        return
      }
      await app.canvas.selectCanvasObject(canvasObject.id)
      return
    }
    await app.canvas.deselectAllCanvasObjects()
    await app.canvas.selectCanvasObject(canvasObject.id)
  }
</script>

{#if canvasObject}
  <div
    id="canvas-object:{canvasObject.id}"
    style:left="{canvasObject.x}px"
    style:top="{canvasObject.y}px"
    class="absolute hover:cursor-grab"
    on:dragstart={handleDragEvent}
    on:drag={handleDragEvent}
    on:dragend={handleDragEvent}
    on:click={handleSelect}
  >
    {#if (canvasObject.informationType = "card")}
      <Card
        information={$information}
        isSelected={canvasObject.isSelected}
        {canvasObject}
      />
    {/if}
  </div>
{/if}
