// src/mindsight/components/canvas/Card.solid.tsx
import { Show, type Component, createEffect } from "solid-js"
import { useMindsight } from "../../Mindsight"
import { createDexieSignalQuery } from "solid-dexie"
import type { PromiseExtended } from "dexie"
import type { IInformation } from "../../interfaces/IInformation"
import { useCanvasObject } from "./contexts/useCanvasObject"
// import { useCanvasObject } from "./contexts/useCanvasObject"

export const Card: Component<{
  id: string
  //canvasObjectId: string
  informationId: string
}> = props => {
  const app = useMindsight()
  const information = createDexieSignalQuery(
    () =>
      app.information.getInformation(props.informationId) as PromiseExtended<
        IInformation | undefined
      >,
  )

  const { registerDragger, canvasObject } = useCanvasObject()

  return (
    <Show when={information() !== undefined}>
      <div
        class="select-none bg-white rounded-1  p-2"
        use:registerDragger={null}
        classList={{
          "border-2 border-blue-5": canvasObject?.()?.isSelected,
        }}
      >
        <div class="w-full h-full">
          <span class="text-3 italic text-coolgray-5 lowercase">
            #{information()?.id}
          </span>
          <h1>{information()?.title}</h1>
        </div>
      </div>
    </Show>
  )
}

// src/mindsight/components/canvas/Card.svelte
<script lang="ts">
  import type { ICanvasObject } from "../../interfaces/ICanvasObject"
  import type { IInformation } from "../../interfaces/IInformation"
  import { registerDragger } from "./CanvasObject.svelte"

  export let information: IInformation
  export let isSelected: boolean
  export let canvasObject: ICanvasObject

  const getSelectedStyle = (isSelected?: boolean) =>
    isSelected ? "border-2 border-blue-500" : ""
</script>

{#if information}
  <div
    class="select-none {getSelectedStyle(isSelected)} bg-white rounded-1 dragger"
    use:registerDragger={canvasObject}
  >
    <div class=" w-full h-full p-2">
      <span
        class="text-3 italic text-coolgray-5 lower"
        on:mousedown={e => {
          e.stopPropagation()
        }}>#{information.id}</span
      >
      <h1>{information.title}</h1>
    </div>
  </div>
{/if}
